# Generated by Django 2.1.5 on 2022-10-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20221023_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
